version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Building the application...
      - python app.py
      - echo Zipping output...
      - zip -r output.zip .  # Zips everything in the current directory
artifacts:
  files:
    - '**/*'
  base-directory: '.'  # Specify where the files are located before zipping
